#!/bin/bash

echo "Checking that SELinux is permanently disabled"
if grep -q "selinux=0" /proc/cmdline; then
    echo "SELinux is permanently disabled, but it should be enabled."
    exit 1
fi

exit 0
