#!/bin/bash

echo "Checking that file /test/a has SELinux type tmp_t"
if ! ls -alZ /test/a | grep -q ":tmp_t:"; then
    echo "File /test/a either has the wrong label or does not exist."
    exit 1
fi

exit 0
